config/routes.rb
Unification::Application.routes.draw do
  devise_for :labs

  scope :controller => 'home' do
    post '/new_student' => :new_student, :as => :new_student
    get '/edit' => :edit, :as => :edit
    put '/update' => :update, :as => :update
  end
  
  root :to => 'home#index'
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :lab
  
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :title_lab, :description, :fields, :students, :director_name, :director_email
  
  has_attached_file :logo, :styles => { :small => "300x150#" }

  has_many :students
  has_many :fields
  
  accepts_nested_attributes_for :students, :reject_if => lambda { |a| a[:mail].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :fields, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :lab
  

end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < Admin::ResourcesController
end

app/controllers/admin/labs_controller.rb
class Admin::LabsController < Admin::ResourcesController
  def create
    # Note that we still can still assign the item to another model. To change
    # this behavior we need only to change how we merge the params.
    item_params = params[:resource] || {}
    item_params.merge!(params[@object_name])

    @item = @resource.new
    @item.assign_attributes(item_params, :as => current_role, :without_protection => true)

    set_attributes_on_create

    respond_to do |format|
      if @item.save
        format.html { redirect_on_success }
        format.json { render :json => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def update
    attributes = params[:_nullify] ? { params[:_nullify] => nil } : params[@object_name]

    respond_to do |format|
      if @item.update_attributes(attributes, :as => current_role, :without_protection => true)
        set_attributes_on_update
        format.html { redirect_on_success }
        format.json { render :json => @item }
      else
        format.html { render :edit }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::ResourcesController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @labs = Lab.all(:include => [:fields, :students])
  end

  def new_student
    lab = Lab.find(params[:student][:lab_id])
    # Remote ip
    lab.students.create(:mail => params[:student][:lab_id], :ip => params[:remote_ip])
    redirect_to :back
  end
  
  def edit
    @lab = Lab.find(current_lab.id, :include => :fields)
    (4 - @lab.fields.count).times {
      @lab.fields.build
    }
  end
  
  def update
    @lab = Lab.find(current_lab.id)
    @lab.update_attributes(params[:lab], :without_protection => true)
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_lab_each.html.erb
<div class="each-labs">
  <% if current_lab.email == lab.email %>
    <div id="edit-lab">
      <%= link_to 'Edit my lab', edit_path %>
    </div>
  <% end %>
  <div id="logo">
    <% if lab.logo.presence %>
      <%= image_tag lab.logo.url(:small), :id => 'logo' %>
    <% else %>
      <div id="no-image"></div>
    <% end %>
  </div>
  <div id="lab-title">
    <%= lab.title_lab %>
    <div style="height:1px;background-color:#B9C0C3; margin-top : 10px;"></div>
    <div style="height:1px;background-color:white;"></div>
  </div>
  <div id="internal-descr">
    <div id="description" class="align-style">
      <%= lab.description %>
    </div>

    <div style="height:1px;background-color:#B9C0C3; margin-top : 10px;"></div>
    <div style="height:1px;background-color:white;"></div>

    <div id="ressources" class="align-style">
      <h3>Ressources</h3>
      <ul>
	<% lab.fields.each do |field| %>
	  <li>
	    <span id="field-title">
	      <%= field.title %>
	    </span>
	    <span id="field-content">
	      <%= link_to field.content, field.content %>
	    </span>
	  </li>
	<% end %>
      </ul>
    </div>

    <div style="height:1px;background-color:#B9C0C3; margin-top : 10px;"></div>
    <div style="height:1px;background-color:white;"></div>

    <div id="director" class="align-style">
      <h3>Directeur</h3>
      <%= lab.director_name %><br/>
      <%= lab.director_email %>
    </div>

    <div style="height:1px;background-color:#B9C0C3; margin-top : 10px;"></div>
    <div style="height:1px;background-color:white;"></div>

    <div id="subscribe" class="align-style">
      <h3>Newlestter</h3>
      <%= form_for :student, :url => new_student_path, :html => {:id => 'special_form'} do |s| %>
      <%= s.text_field :mail, :placeholder => 'Votre email' %>
      <%= s.hidden_field :lab_id, :value => lab.id %>
      <%= s.submit "S'inscrire" %>
<% end %>
</div>

</div>
</div>

app/views/home/edit.html.erb
<center>
  <h1 style="font-size : 25px; margin-bottom : 20px"><%= current_lab.title_lab %> edit</h1>
</center>


<div style="width : 960px; margin : 0 auto;">
<%= semantic_form_for @lab, :url => update_path do |f| %>
  <%= f.inputs :title_lab, :description, :logo, :director_email, :director_name %>
 
  <h3>Ressources</h3>
  <%= f.semantic_fields_for :fields do |field| %>
    <div style="height:1px;background-color:#B9C0C3; margin-top : 10px;"></div>
    <div style="height:1px;background-color:white; margin-bottom : 5px;"></div>
    <%= field.inputs :title, :content %>
  <% end %>

  <%= f.button :submit %>
<% end %>

</div>

app/views/home/edit2.html.erb
<%= form_for @lab, :url => update_path, :multipart => true  do |l| %>
  <%= l.label :director_name %><br/>
  <%= l.text_field :director_name %> <br/>
  
  <%= l.label :director_email %><br/>
  <%= l.text_field :director_email %> <br/>
  
  
  <%= l.label :title_lab %><br/>
  <%= l.text_field :title_lab %><br/>

  <%= l.label :description %><br/>
  <%= l.text_area :description %><br/>


  <%= l.label :logo %><br/>
  <%= l.file_field :logo %><br/>
  
  



  <%= l.fields_for :fields, @lab.fields do |builder| %>
    <%= builder.text_field :content %>
  <% end %>

  <!-- <div id="fields"> -->
  <!--   <h3>Fields</h3> -->
  <!--   <ul> -->
  <!--   <% current_lab.fields.each do |f| %> -->
  <!--     <li> -->
  <!-- 	<%= f.title %> -->
  <!-- 	<%= f.content %> -->
  <!--     </li> -->
  <!--   <% end %> -->
  <!--   </ul> -->
  <!--   <div id="new_field"> -->
  <!--     APPEND -->
  <!--   </div> -->
  <!-- </div> -->
<% end %>

app/views/home/index.html.erb
<div id="labs">
  <% @labs.each do |lab| %>
    <%= render :partial => 'home/lab_each', :locals => {:lab => lab } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>